/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    screens: {
      // Standard breakpoints (ascending order)
      xxxs: "240px",
      "mobile-xxs": "280px",
      "mobile-sm": "320px",
      xxs: "320px",
      "mobile-xs": "340px",
      "xxs-plus": "350px",
      xs: "375px",
      "xs-plus": "400px",
      "mobile-md": "414px",
      xsm: "450px",
      sm: "480px",
      "sm-plus": "520px",
      "sm-md": "560px",
      "mobile-lg": "560px",
      "md-minus": "600px",
      "tablet-xs": "600px",
      "tablet-sm": "640px",
      "pre-md": "680px",
      "tablet-md": "720px",
      md: "768px",
      "md-plus": "850px",
      "md-lg": "900px",
      "tablet-lg": "900px",
      "almost-lg": "950px",
      "laptop-xs": "1000px",
      lg: "1024px",
      "lg-plus": "1100px",
      "pre-xl": "1200px",
      "laptop-sm": "1200px",
      xl: "1280px",
      "xl-plus": "1366px",
      "laptop-md": "1366px",
      "1.5xl": "1440px",
      "laptop-lg": "1440px",
      "2xl": "1536px",
      desktop: "1600px",
      "2xl-plus": "1680px",
      "desktop-md": "1680px",
      "desktop-lg": "1800px",
      "3xl": "1920px",
      "desktop-xl": "2160px",
      "4xl": "2560px",
      ultrawide: "2560px",
      "4k": "3840px",
    },
    extend: {
      colors: {
        primary: "var(--primary)",
        "chartreuse-green-60": "var(--color-chartreuse-green-60)",
        "white-solid": "var(--color-white-solid)",
        "black-solid": "var(--color-black-solid)",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "system-ui", "sans-serif"],
      },
      spacing: {
        128: "32rem",
        144: "36rem",
      },
    },
  },
  plugins: [],
};
